name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      CHANGELOG_FILE: CHANGELOG.md
      RELEASE_NOTES_FILE: release_notes.md
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest

      - name: Extract release notes
        shell: bash
        run: |
          set -euo pipefail
          release_tag="${{ github.ref_name }}"
          awk -v tag="$release_tag" '
            index($0, "## [" tag "]") == 1 { collecting=1; next }
            collecting && index($0, "## [") == 1 { collecting=0 }
            collecting
          ' "$CHANGELOG_FILE" > "$RELEASE_NOTES_FILE"
          if [ ! -s "$RELEASE_NOTES_FILE" ]; then
            echo "No release notes found for tag $release_tag in $CHANGELOG_FILE" >&2
            exit 1
          fi

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          body_path: ${{ env.RELEASE_NOTES_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
